server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
    mongodb:
      uri: mongodb+srv://adminms:Boyano88@cluster0.gp70h.mongodb.net/productos?retryWrites=true&w=majority
  application:
    zipkin: http://localhost:9411
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka