server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-microservicio
          uri: lb://usuario-microservicio
          predicates:
            - Path=/v1/usuarios/**
        - id: auto-microservicio
          uri: lb://auto-microservicio
          predicates:
            - Path=/v1/autos/**
        - id: moto-microservicio
          uri: lb://moto-microservicio
          predicates:
            - Path=/v1/motos/**