server:
  port: 8091
spring:
  cloud:
    config:
      server:
        git:
          default-label: configuraciones
          uri: https://github.com/kristianortizlemus88/microservicios-uno
          search-paths: datos-configuracion
  application:
    name: servicio-configuracion
