server:
  port: 8082
spring:
  application:
    name: moto-microservicio
  data:
    mongodb:
      uri: mongodb+srv://adminms:Boyano88@cluster0.gp70h.mongodb.net/productos?retryWrites=true&w=majority
